### ISSUE TITLE
Swipe to Exit

### ISSUE THREAD

**Issue by RB-King** [AdamBCo/ABCIntroView#5]
That's Good and Easy Demo. really nice.
But i want to one more thing, When i scroll 4 introscreen than i want exit and redirect on other viewcontroller. please say me code about that and help me....
Thank x in advance...

**Comment by AdamBCo** [comment]
Hey @JaydeepPatel sorry about the late reply!

For simplistic purposes, I would recommend creating a UIScrollView with 5 embedded UIViews. When the user is presented with the 5th view, you can animate the alpha and remove it from the superview. 

I hope that helps! 👍
